variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - deploy

hugo:
  stage: build
  image: ruby:latest
  before_script:
    - bundle install --jobs=3 --retry=3
    - wget https://github.com/gohugoio/hugo/releases/download/v0.71.0/hugo_0.71.0_Linux-64bit.deb
    - apt install ./hugo_0.71.0_Linux-64bit.deb -y
  script:
    - hugo

    # Dirty hack. Probably there is a better solution
    - echo "madhead.me" > public/en/CNAME
    - echo "ru.madhead.me" > public/ru/CNAME
  artifacts:
    name: $CI_COMMIT_SHA-$CI_JOB_NAME
    paths:
      - public
    expire_in: 1 hour

pages:
  stage: deploy
  image: alpine:latest
  variables:
    GIT_STRATEGY: none
  script:
    - /bin/true
  artifacts:
    paths:
      - public
  environment:
    name: staging
    url: https://madhead.me.gitlab.io/madhead.me

production:
  stage: deploy
  image:
    name: alpine/git:latest
    entrypoint: ["/bin/sh", "-c"]
  variables:
    GIT_STRATEGY: none
  before_script:
    - git config --global user.name  'GitLab'
    - git config --global user.email '<>'
    - mkdir ~/.ssh
    - ssh-keyscan github.com >> ~/.ssh/known_hosts
    - eval $(ssh-agent -s)
  script:
    - cd public/ru
    - ssh-add -D
    - echo "$DEPLOY_KEY_RU" | tr -d '\r' | ssh-add - > /dev/null
    - git init
    - git remote add origin git@github.com:madhead/ru.madhead.github.io.git
    - git add .
    - git commit --allow-empty-message --message ''
    - git push origin master -f
    - cd ../en
    - ssh-add -D
    - echo "$DEPLOY_KEY_EN" | tr -d '\r' | ssh-add - > /dev/null
    - git init
    - git remote add origin git@github.com:madhead/madhead.github.io.git
    - git add .
    - git commit --allow-empty-message --message ''
    - git push origin master -f
    - ssh-agent -k
  environment:
    name: production
    url: https://madhead.me
  only:
    - master
