---
baseurl: https://madhead.me/

theme: minimo

languages:
  en:
    languageName: EN
    contentDir: content/en
    weight: 1
    baseurl: https://madhead.me/
    googleAnalytics: UA-101212543-1
    menu:
      sidebar:
        - identifier: posts
          name: posts
          url: /posts/
          weight: 1
        - identifier: tags
          name: tags
          url: /tags/
          weight: 2
  ru:
    languageName: RU
    contentDir: content/ru
    weight: 2
    baseurl: https://ru.madhead.me/
    googleAnalytics: UA-101212543-2
    menu:
      sidebar:
        - identifier: posts
          name: посты
          url: /posts/
          weight: 1
        - identifier: tags
          name: теги
          url: /tags/
          weight: 2

enableRobotsTXT: true

disqusShortname: madhead-me

taxonomies:
  tag: tags

preserveTaxonomyNames: true

paginate: 10
buildFuture: true

title: madhead

params:
  settings:
    accentColor: "#000000"
    showReadingTime: true
    hideEntryNavigation: true
    dateFormat: 2006-01-02
    archiveDateFormat: 2006-01-02
    listDateFormat: 2006-01-02
  sidebar:
    enable: true
  social:
    email: siarhei.krukau@gmail.com
    gitlab: madhead
    github: madhead
    stackoverflow: 750510
    telegram: madheab
    linkedin: krukaus
    instagram: m.a.d.h.e.a.d
    youtube: UCO2UZ6hUzjn9XQIdwwkcXJQ
    twitter: m_a_d_h_e_a_d
  comments:
    enable: true
  widgets:
    sidebar:
      - about
      - sidebar_menu
      - social_menu
  monetization: $ilp.uphold.com/wgzRi7wDbPFf
  assets:
    customCSS:
      - css/admonitions.css

menu:
  sidebar:
    - identifier: posts
      name: posts
      url: /posts/
      weight: 1
    - identifier: tags
      name: tags
      url: /tags/
      weight: 2

security:
  exec:
    osEnv:
      - (?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM|GEM_PATH)$
    allow:
      - asciidoctor
