---
baseurl:          https://madhead.me/

theme:            minimo

enableRobotsTXT:  true

googleAnalytics:  UA-101212543-1
disqusShortname:  madhead-me

taxonomies:
  tag:            tags

preserveTaxonomyNames: true

paginate:         10

params:
  settings:
    accentColor:  '#000000'
    showReadingTime: true
    hideEntryNavigation: true
    dateFormat: 2006-01-02
    archiveDateFormat: 2006-01-02
    listDateFormat: 2006-01-02
  sidebar:
    enable:       true
  social:
    github: madhead
    gitlab: madhead
    twitter: madhead_
    instagram: madhead_
    youtube: UCO2UZ6hUzjn9XQIdwwkcXJQ
    linkedin: krukaus
    telegram: xXmadheadXx
  widgets:
    sidebar:
      - about
      - sidebar_menu
      - social_menu
    homepage:
menu:
  sidebar:
    - identifier: posts
      name:       posts
      url:        /posts/
    - identifier: tags
      name:       tags
      url:        /tags/
