---
baseurl:          https://madhead.me/

theme:            minimo

enableRobotsTXT:  true

googleAnalytics:  UA-101212543-1
disqusShortname:  madhead-me

taxonomies:
  tag:            tags

preserveTaxonomyNames: true

paginate:         10

title: madhead

params:
  settings:
    accentColor:  '#000000'
    showReadingTime: true
    hideEntryNavigation: true
    dateFormat: 2006-01-02
    archiveDateFormat: 2006-01-02
    listDateFormat: 2006-01-02
  sidebar:
    enable:       true
  social:
    email: siarhei.krukau@gmail.com
    gitlab: madhead
    github: madhead
    stackoverflow: 750510
    telegram: xXmadheadXx
    linkedin: krukaus
    instagram: madhead_
    youtube: UCO2UZ6hUzjn9XQIdwwkcXJQ
    twitter: madhead_
  comments:
    enable: true
  widgets:
    sidebar:
      - about
      - sidebar_menu
      - social_menu
menu:
  sidebar:
    - identifier: posts
      name:       posts
      url:        /posts/
      weight:     1
    - identifier: tags
      name:       tags
      url:        /tags/
      weight:     2
    - identifier: cv
      name:       cv
      url:        /cv/
      weight:     3
