version: '3.8'

services:
  hugo:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1313:1313"
    volumes:
      - .:/src
    working_dir: /src
    command: serve --bind=0.0.0.0 --poll 1s --disableFastRender
