---
title: 'Fear and loathing of server-side App Store receipts validation'
date: 2020-06-03T09:00:00+03:00
tags:
  - app store
  - pain
---

Some time ago, I wrote a link:../appstore-receipts-validator-j[blogpost] about my https://gitlab.com/madhead/appstore-receipts-validator-j[Java library for App Store receipts validation].
Recently, I was contacted by another developer working on a server-side App Store receipts validation.
He found my article and then contacted me in Telegram, we had a pretty long conversation and discussed a lot of nuances.
I never thought that receipt validation could be of some interest, but after that conversation I realized how much pain I have expirienced and how much intricacies are there in this task.

So here it is: everything I wish I knew about server-side App Store receipts validation before I did it for the first time.

<!--more-->

## Contents

* <<disclaimer, Disclaimer>>
* <<intro, Server-side receipts validation>>
* <<receipts, App Store receipts>>
* <<docs, Apple documentation>>
* <<docs, Apple documentation>>

[#disclaimer]
## Disclaimer

I am not an expert and I may be wrong.
I may misunderstood some concepts.
Everything I say here is my personal opinion based on my personal expirience.
The information I provide here may be obsolete, always keep in mind the https://developer.apple.com/documentation/storekit/in-app_purchase/validating_receipts_with_the_app_store[official] https://developer.apple.com/documentation/appstorereceipts[documentation].

[#intro]
## Server-side receipts validation

Let's talk about receipts and their validation first.

In this article, by App Store receipt (or just receipt) I mean a piece of information about a purchase made from within the app.
Thus, by employing receipt validation techniques you can authenticate purchased content.

There are two receipt validation techniques: on-device receipt validation and server-side receipt validation.
A developer should https://developer.apple.com/documentation/storekit/in-app_purchase/choosing_a_receipt_validation_technique[compare both approaches] and determine the best fit his app.
He can also choose to implement both.

I'll be talking solely about server-side receipt validation in this article.

From the server-side point of view, a receipt is just a long string, like:

[source]
----
MIIcSAYJKoZIhvcNAQcCoIIcOTCCHDUCAQExCzAJBgUrDgMCGgUAMIIL+QYJKoZIhvcNAQcBoIIL6gS
…9622 symbols skipped…
J8rloluUN2JvNwiFzPY0eAtCToLpBfGdL2I3ymDFJWiQbCuuNRa/PfGBFpMc0PGSqyQ0C5GFULTDVU=
----

### What & Why?
### 2 types of recipes, why it's important

[#receipts]
## App Store receipts

[#docs]
## Apple documentation

### Docs


HTML instead of JSON
How to detekt new transactions / groups
Incrementing transaction ids (bug?)
How to check expired subscriptions / Useless S2S
https://medium.com/revenuecat-blog/ios-subscriptions-are-hard-d9b29c74e96f
204 S2S
No money in /verifyReceipt
Fastlane / spaceship
