---
title: Как читать книги
date: 2021-03-07T18:00:00+03:00
tags:
  - книги
rating: 4
---

Конспект книги https://www.goodreads.com/book/show/10794379["Как читать книги"] от Сергея Иннокентьевича Поварнина.

В целом довольно очевидные вещи, но поданы чётко и по делу, без лишней воды, как у link:../how-not-to-write-a-book[Мортимера], да и применимы к чтению любых книг, а не только __великих__.
Отсюда и ⅘.

<!--more-->

== Цели чтения

* Низшая группа целей:
** Чтение для того, чтобы убить время
** Для отвлечения от неприятных мыслей
** Для развлечения
** Чтобы заснуть
* Высшая группа целей:
** Для осведомления
** Для воодушевления
** Чтение крупных произведений искусства
** Для изучения какого‐нибудь вопроса
** Для самообразования

== Способы чтения

[quote]
____
Способ чтения зависит от цели чтения и всецело ею обусловливается.
____

____
Отчетливое чтение — обязательное условие хорошего чтения.
____

* По трудозатратам: 
** Пролистать книгу
** Просмотреть, пробежать книгу
** Неполное, выборочное чтение
** Полное чтение
** Полное чтение с проработкой
* По отношению к содержимому книги:
** Пассивное чтение (с безусловным принятием содержимого)
** Активное чтение (с оценкой и критикой)
* По глубине:
** Поверхностное
** Углубленное

== Работа над книгой

[quote]
____
Образованный от необразованного отличается больше всего не количеством сведений.

…

Только сравнительно немногие понимают это и стараются не только наполнять память, но и главным образом — дисциплинировать и упражнять ум, приобретать навык к систематическому отчетливому мышлению.
____

. Понять
. Оценить
. Подвергнуть критике
. Проработать рассуждения автора и усвоить его методы

== Необходимые условия для правильного чтения

* Наличие известных способностей
** Способность сосредоточивать и удерживать внимание на читаемом
** Память
* Отсутствие дурных навыков в чтении
** Ослабление внимания
*** Привычка, читая книгу, думать о другом
** Небрежное чтение
** Привычка только пробегать книги
** Чтение запоем
** Глотание книг
** Нетерпеливость
*** Привычка бросать книги
*** Пропуски при чтении
** Лень мышления и воображения
+
[quote]
____
Читать с наименьшим усилием, с наименьшим напряжением мысли и воображения — вот нередкая склонность. И она — величайшая помеха при чтении.
____

== Общие указания о том, что читать для самообразования

* Когда количество чтения начинает отзываться на качестве, следует предпочесть последнее
* Читать только лучшие книги, какие можно достать
* Выбирать самое нужное и необходимое
* Не читать ни слишком легких, ни слишком трудных книг
* Придерживаться определенного плана
** Начать с хорошего краткого учебника по теме, потом проработать хорошее руководство

== Вдохновляющие книги

* Такие книги приходится читать пассивным чтением
* Впитать в себя мысли и настроения
* После каждого чтения подумать, как полученные импульсы, побуждения, стремления применить к делу, к нашей жизни в теперешней ее обстановке
* Переведенная в действие мысль — основа хорошего навыка, не переведенная — часто шаг к созданию мечтателя

== Чтение произведений искусства

* Мы переживаем лучше всего художественные произведения лишь тогда, когда читаем вполне пассивно

== Перечитывание

* Читаемое первый paз произведение имеет для нас огромный интерес.
* При перечитывании этот интерес отпадает, взамен мы обращаем внимание на другие стороны, более существенные.
* Настоящее переживание и понимание художественного произведения возможно только при перечитывании.

== Чтение критики

* Критику на читаемое с целью самообразования не следует брать в руки раньше прочтения самой книги
** Это ослабляет, иногда убивает самодеятельность, заставляя невольно смотреть на книгу через чужие очки
* Если книга читается не в целях самообразования, часто приходится н необходимо идти обратным путем

== Предварительное ознакомление с книгой

* Предварительное ознакомление с книгой перед настоящим чтением и проработкой ее дает сбережение времени и труда и лучшие результаты

== Обзор содержания книги

* Для того, чтобы предварительно получить общее впечатление от книги необходим oбзоp ее содержания
* Тему обыкновенно указывает уже заглавие книги
* Главную мысль и все остальное приходится искать другими путями — в предисловии, введении, оглавлении, заключении книги.

== Просмотр книги

* Многие книги нам приходится только просматривать
* Некоторые из них и не стоят полного чтения
* Но и в этом случае полезно начинать с обзора, то есть с чтения предисловия, введения, особенно конца его, и заключительных строк книги, ознакомиться с оглавлением, а затем уже перелистывать и просматривать самую книгу.

== Главные задачи проработки книги

. Книга должна быть правильно и отчетливо понята
. Мысли и сведения, содержащиеся в ней, должны отработать в нашем уме
. Во многих случаях должна быть произведена оценка ее содержания.

== Понимание книги

* Опаснее всего иллюзия понимания
* Первое условие понимания книги — достаточная подготовка
* Второе условие — понимание иностранных слов и научных терминов
* Третье условие — уменье вникать в читаемое

== Отработка содержания книги

* Первый тип. Содержание книги может быть усвоено нами.
* Второй тип — противоположный. Мы не признаем содержания книги истинным. Мы отвергаем его, так как оно кажется ошибочным или несовместимым с нашими взглядами.

== Продумывание книги

* Чем больше наших собственных мыслей, знаний, эмоций вовлекается в эту работу, тем больше результаты, тем глубже продумывание. Тем полезнее оно для самообразования и для умственного развития.
* Полезно и даже необходимо создать привычку сознательного и намеренного продумывания, продумывания в настоящем смысле слова.
** Не читать без передышек, параграф за параграфом, главу за главою.
** Уметь некоторое время поддерживать внимание на одном и том же вопросе.
* Прочитав интересную мысль
.. остановиться на ней
.. подумать о ней
.. прислушаться к тем новым мыслям
.. поставить вопрос, верна она или нет
.. напрячь свои силы, развить, если потребуется, мысль дальше
* Мысли, которые приходят нам в голову при чтении — записать

== Оценка и критика книги

* Ставить, на каждом шагу вопpoc: так или не так?
* Настоящая критика требует не только смелости, но и знания, и труда.
* После прочтения и разработки книги и своей критики ее прочесть основательную критику на нее какого‐нибудь крупного специалиста.

== Процесс чтения

* От общего впечатления идти к частям, к подробностям
* Очень полезно, принимаясь за проработку главы, предварительно пробежать ее, ознакомиться с общим содержанием
* Cpaвниваем самостоятельно составленный содержание главы с перечнем автора, при наличии, и рассматриваем, в чем различие, почему автор выделил иную тему, чем мы, прав ли он и т. д.

== Усвоение параграфа

* Отчетливо понять — значит уметь точно и ясно определить его тему и кратко изложить ответ на нее
* Понять доказательство — значит отчетливо выяснить, тезис, какие именно приводятся основания и как вытекает из них тезис.
* Критиковать доказательство — значит доказывать неприемлемость оснований или отсутствие связи их с тезисом
* Рисунки и чертежи очень важны для понимания многих книг.

== Охватывание книги

* Окончив книгу, читатель должен охватить ее, получить от нее общее, полное и отчетливое в основных подробностях впечатление

== Основное содержание книги

* Постараться в самых кратких словах, точно, по возможности письменно, сформулировать главную мысль или сущность, основное содержание ее.
* После прочтения книги восстановить в общих чертах в памяти и схему ее содержания по оглавлению или по конспектам; постараться охватить все прочитанное содержание ее как целое: еще раз отчетливо вникнуть в её план;
* Если велись попутные конспекты по главам или по отделам, чрезвычайно полезно переработать их в один цельный конспект всей книги.
* Если к книге приложен предметный указатель, то полезно взять из него наиболее важные для нас вопросы и постараться отдать себе отчет, что именно сказано автором на эту тему.

== Чтение книг противоположного содержания

* После прочтения с проработкой одной книги очень важно и полезно прочитать, если есть, книгу на ту же тему, но противоположного направления.
* Для многих чрезвычайно плодотворным оказывается параллельное чтение двух книг, особенно различных или даже противоположных по взглядам. 

== Коллективное чтение

* Оно полезно, если не нарушает самодеятельности участников, главным образом когда каждый участник предварительно сам проработал вопрос или книгу так, как было указано выше.
* Если кружок берет какой‐нибудь вопрос и участник прорабатывает свой материал вроде того, как описано выше, а потом уже ведется обсуждение, — такая работа, конечно, в высшей степени желательна и в высшей степени полезна для участников.
* Но она не может заменить отдельной работы, а лишь дополняет и улучшает ее.

== Перечитывание важнейших книг

* Для глубокого изучения книги совершенно недостаточно прочитать ее один раз.

== Вспомогательные средства чтения

* Указатель книги
* Оглавление
* Подчеркивание и отчеркивание
* Конспект
** Выделить из книги все существенное, основное;
** Связно изложить
** Материал, взятый у автора, излагать при конспектировании в другом порядке, как удобнее
** Чем больше и глубже эта переработка, тем, конечно, она труднее, тем большего требует продумывания
* Выписки
* Запись своих мыслей
* Журнал чтения
* Указатель по вопросу
