---
title: A human guide to writing netdata plugins
date: 2018-09-16T04:45:00+03:00
tags:
  - netdata
  - kotlin
---

A month ago I learned about https://my-netdata.io[netdata] — simple monitoring tool for Linux.
It's really great and it saved my ass several times already for that short month.
A few days ago I decided to extend it with my own plugin for custom metrics, and here is my experience.

<!--more-->

=============================

Netdata is a configuration-less tool. As already told, it is ready to use right after installation. But The term “configuration-less” means much more than this. It’s fascinating meaning is that it can run without any configuration file. If you don’t believe this, delete your /etc/netdata/netdata.conf file, and run netdata. It will still be working. Read here why it works.

=============================

As I've said, netdata is great.
But it's documentation is poor.
https://github.com/firehol/netdata/wiki/Writing-Plugins[Writing a plugin] is not hard, but I was not able to find a good end-to-end guide, so I made one.

== Basics

netdata plugins can be written in any language: C/C++, Go, Java, Python, Ruby, JS (Node.js) and others.
Obviously, a third-party plugin written in arbitrary language will be started in a separate process, netdata's child.
The way it communicates with netdata raises the only requirement for all plugins: a plugin, when started and running, must be able to write strings to it's `stdout` and `stderr`.
That's not a big deal unless you're doing true functional programming ;)
Plugin's `stdout` will be connected through a pipe to netdata.
netdata will read commands from this pipe and turn them into charts and data points.
Plugin's `stderr` will be sent to the netdata's error log.
That's basically, the "protocol" at a glance.

Due to a high cost of process creation and, probably, resources initialization, plugins have to be designed in a way to stay alive once started until netdata decides to stop them.

To summarize, here is a sequence diagram of a plugin's interaction with netdata.

[source]
----
    ┌─────────────┐                  ┌─────────────┐
    │   netdata   │                  │   plugin    │
    └──────┬──────┘                  └──────┬──────┘
           │                                │
           │ Spawns plugin process          │
           ├───────────────────────────────>│
           │                                │
           │                                │
           │                                │ Performs
           │                                ├───────────────────╮
           │                                │ initialization    │
           │                                │                   │
           │                                │<──────────────────╯
           │                                │
           │                                │
    ╭────┬─┼────────────────────────────────┼─────╮
    │loop│ │                                │     │
    ├────╯ │                     Sends data │     │
    │      │<───────────────────────────────┤     │
    ╰──────┼────────────────────────────────┼─────╯
           │                                │
           │                                │
           │                                │
           │                                │
           │                                │
           │                                │
           │ Kills plugin process           │
           ├───────────────────────────────>│
           │                                ╳
           │
----

netdata kills misbehaving plugins — those who output litter or crash with non-zero return codes.
netdata will restart a plugin that exited normally (with zero exit code).
