name: Dead links

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  dead-links:
    name: Dead links
    runs-on: ubuntu-latest
    strategy:
      matrix:
        site:
          - https://madhead.me
          - https://ru.madhead.me
    steps:
      - name: ${{ matrix.site }}
        uses: ruzickap/action-my-broken-link-checker@v2.3.0
        with:
          url: ${{ matrix.site }}
