name: Dead links

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  dead-links:
    name: Dead links
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        site:
          - https://madhead.me
          - https://ru.madhead.me
    steps:
      - name: ${{ matrix.site }}
        uses: ruzickap/action-my-broken-link-checker@v2.3.1
        with:
          url: ${{ matrix.site }}
          cmd_params: >-
            --rate-limit=10
            --max-connections-per-host=5
            --buffer-size=8192
            --header="User-Agent: curl/7.81.0"
            --ignore-fragments
            --exclude="localhost"
            --exclude=".*madhead\.me\/cdn-cgi\/l\/email\-protection.*"
            --exclude="linkedin"
