name: Default

on:
  push:
    branches-ignore:
      - master

jobs:
  default:
    name: Default
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: latest
          extended: true

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - run: gem install asciidoctor

      - run: hugo
