name: Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0

      - uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: latest
          extended: true

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.2
          bundler-cache: true

      - run: gem install asciidoctor

      - run: hugo

      - uses: actions/upload-artifact@v2
        with:
          name: en
          path: public/en
      - uses: actions/upload-artifact@v2
        with:
          name: ru
          path: public/ru

  deploy-en:
    name: Deploy (EN)
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: Production (EN)
      url: https://madhead.me
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: en
          path: public/en

      - uses: peaceiris/actions-gh-pages@v3
        with:
          external_repository: madhead/madhead.github.io
          deploy_key: ${{ secrets.EN_SITE_DEPLOY_KEY }}
          publish_dir: public/en
          publish_branch: master
          cname: madhead.me

  deploy-ru:
    name: Deploy (RU)
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: Production (RU)
      url: https://ru.madhead.me
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: ru
          path: public/ru

      - uses: peaceiris/actions-gh-pages@v3
        with:
          external_repository: madhead/ru.madhead.github.io
          deploy_key: ${{ secrets.RU_SITE_DEPLOY_KEY }}
          publish_dir: public/ru
          publish_branch: master
          cname: ru.madhead.me
