name: Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: https://madhead.me
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0

      - uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: latest
          extended: true

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.2
          bundler-cache: true

      - run: gem install asciidoctor

      - run: hugo

      - run: echo "madhead.me" > public/en/CNAME
      - run: echo "ru.madhead.me" > public/ru/CNAME

      - uses: peaceiris/actions-gh-pages@v3
        with:
          external_repository: madhead/ru.madhead.github.io
          deploy_key: ${{ secrets.RU_SITE_DEPLOY_KEY }}
          publish_dir: ./public/ru
          publish_branch: master
      - uses: peaceiris/actions-gh-pages@v3
        with:
          external_repository: madhead/madhead.github.io
          deploy_key: ${{ secrets.EN_SITE_DEPLOY_KEY }}
          publish_dir: ./public/en
          publish_branch: master
